### ISSUE TITLE
HELPPPP!!! - python, c++ issue

### ISSUE THREAD

**Issue by angiesasmita** [whizzzkid/opencv-complete-build-cuda#1]
Hi Whizzkid!

First of all thanks a lot for this repo. I have been trying to build opencv from source for two days and using your scripts is the first time I could build it successfully. 

I'm relatively new to openCV, so pardon my potentially dumb question. 

1) In this guide you mention: $HOME/.opencv/lib/pythonX.X/dist-package
but I can't seem to find .opencv file in my directory. So not sure which python version I should put it in. 

2) does it mean that the library compiled only work for python project? (using import in python script)? How about for C++ projects? Does it need to be added into environment or sth? I was trying to call open cv through "#include <opencv2/core/version.hpp>" but couldn't make it work. or do I need to put the folder somewhere inside the project?

I'm trying to do a python opencv with cuda accel, using https://github.com/alexanderkoumis/opencv-gpu-py . but I couldn't build the opencv through his guide. 

Please helpppppp :( THANKS A LOTT!!

**Comment by whizzzkid** [comment]
Are you sure the build completed, because there aren't any checks in the script to make sure everything was built. You might wanna check the logs again to see if everything was built.

> In this guide you mention: $HOME/.opencv/lib/pythonX.X/dist-package
but I can't seem to find .opencv file in my directory. So not sure which python version I should put it in.

The .opencv build would be in your $HOME directory, generally denoted by tild `~`. So try `$ cd ~/.opencv` and you should have all the build binaries here. now you need to create $PYTHONPATH global variable and the dist-package to that.

> does it mean that the library compiled only work for python project? (using import in python script)? How about for C++ projects? Does it need to be added into environment or sth? I was trying to call open cv through "#include <opencv2/core/version.hpp>" but couldn't make it work. or do I need to put the folder somewhere inside the project?

No, python build flags are extra. you can use it with c++ easily by doing something like: https://docs.opencv.org/2.4/doc/tutorials/introduction/linux_gcc_cmake/linux_gcc_cmake.html

Hope this helps.

**Comment by angiesasmita** [comment]
I'm not sure how to check the log, so I'm rebuilding it again... 
Btw, if it can't be used for python, why python global var need to be set? and how do I go about adding python flag?

**Comment by angiesasmita** [comment]
I realised that the first time, the build wasn't started. this time, there's my error in my build:

`[  8%] Linking CXX static library ../lib/libIlmImf.a
[  8%] Built target IlmImf
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2
Mon Nov 20 10:30:08 +08 2017: Installing OpenCV
[  0%] Built target gen-pkgconfig
[  1%] Built target ippiw
[  3%] Built target libjasper
[  3%] Built target ittnotify
[  4%] Building CXX object modules/sfm/src/libmv/libmv/numeric/CMakeFiles/numeric.dir/numeric.cc.o
[  6%] Built target IlmImf
[  5%] Building CXX object modules/sfm/src/libmv/libmv/numeric/CMakeFiles/numeric.dir/poly.cc.o
Scanning dependencies of target opencv_cudev
[  6%] Building CXX object modules/cudev/CMakeFiles/opencv_cudev.dir/src/stub.cpp.o
[  6%] Built target gen_opencv_python3
[  6%] Built target gen_opencv_python2
[  8%] Built target libprotobuf
[  8%] Linking CXX shared library ../../lib/libopencv_cudev.so
[  8%] Built target opencv_cudev
[  9%] Building NVCC (Device) object modules/core/CMakeFiles/cuda_compile.dir/src/cuda/cuda_compile_generated_gpu_mat.cu.o
[  9%] Processing OpenCL kernels (core)
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
In file included from /home/angelita/Downloads/opencv_contrib/modules/sfm/src/libmv_light/libmv/numeric/numeric.cc:22:0:
/home/angelita/Downloads/opencv_contrib/modules/sfm/src/libmv_light/libmv/numeric/numeric.h: In function ‘bool libmv::__builtin_isnan(double)’:
/home/angelita/Downloads/opencv_contrib/modules/sfm/src/libmv_light/libmv/numeric/numeric.h:461:10: error: ‘__builtin_isnan’ is not a member of ‘std’
   return std::isnan(i);
          ^
/home/angelita/Downloads/opencv_contrib/modules/sfm/src/libmv_light/libmv/numeric/numeric.h:461:10: note: suggested alternatives:
<built-in>:0:0: note:   ‘__builtin_isnan’
In file included from /usr/include/c++/4.8/cmath:44:0,
                 from /usr/include/c++/4.8/complex:44,
                 from /usr/include/eigen3/Eigen/Core:80,
                 from /usr/include/eigen3/Eigen/Cholesky:11,
                 from /home/angelita/Downloads/opencv_contrib/modules/sfm/src/libmv_light/libmv/numeric/numeric.h:28,
                 from /home/angelita/Downloads/opencv_contrib/modules/sfm/src/libmv_light/libmv/numeric/numeric.cc:22:
/home/angelita/Downloads/opencv_contrib/modules/sfm/src/libmv_light/libmv/numeric/numeric.h:457:13: note:   ‘libmv::__builtin_isnan’
 inline bool isnan(double i) {
             ^
modules/sfm/src/libmv/libmv/numeric/CMakeFiles/numeric.dir/build.make:62: recipe for target 'modules/sfm/src/libmv/libmv/numeric/CMakeFiles/numeric.dir/numeric.cc.o' failed
make[2]: *** [modules/sfm/src/libmv/libmv/numeric/CMakeFiles/numeric.dir/numeric.cc.o] Error 1
CMakeFiles/Makefile2:17674: recipe for target 'modules/sfm/src/libmv/libmv/numeric/CMakeFiles/numeric.dir/all' failed
make[1]: *** [modules/sfm/src/libmv/libmv/numeric/CMakeFiles/numeric.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
Scanning dependencies of target opencv_core
[  9%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/alloc.cpp.o
[  9%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/algorithm.cpp.o
[  9%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/arithm.cpp.o
[  9%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/conjugate_gradient.cpp.o
[  9%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/array.cpp.o
[  9%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/convert.cpp.o
[  9%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/command_line_parser.cpp.o
[  9%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/copy.cpp.o
[  9%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/cuda_gpu_mat.cpp.o
[  9%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/cuda_host_mem.cpp.o
[  9%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/cuda_info.cpp.o
[  9%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/cuda_stream.cpp.o
[  9%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/datastructs.cpp.o
[  9%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/directx.cpp.o
[  9%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/downhill_simplex.cpp.o
[  9%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/dxt.cpp.o
[  9%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/gl_core_3_1.cpp.o
[  9%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/glob.cpp.o
[  9%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/hal_internal.cpp.o
[  9%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/kmeans.cpp.o
[  9%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/lapack.cpp.o
[  9%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/lda.cpp.o
[  9%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/lpsolver.cpp.o
[  9%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/mathfuncs.cpp.o
[  9%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/mathfuncs_core.dispatch.cpp.o
[  9%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/matmul.cpp.o
[  9%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/matop.cpp.o
[  9%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/matrix.cpp.o
[ 10%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/matrix_decomp.cpp.o
[ 10%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/merge.cpp.o
[ 10%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/ocl.cpp.o
[ 10%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/opencl/runtime/opencl_clamdblas.cpp.o
[ 10%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/opencl/runtime/opencl_clamdfft.cpp.o
[ 10%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/opencl/runtime/opencl_core.cpp.o
/home/angelita/Downloads/opencv/modules/core/src/opencl/runtime/opencl_core.cpp:337:7: warning: extra tokens at end of #else directive [enabled by default]
 #else HAVE_OPENCL_STATIC
       ^
[ 10%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/opengl.cpp.o
[ 10%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/out.cpp.o
[ 10%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/ovx.cpp.o
[ 10%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/parallel.cpp.o
[ 10%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/parallel_pthreads.cpp.o
[ 10%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/pca.cpp.o
[ 10%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/persistence.cpp.o
[ 10%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/rand.cpp.o
[ 10%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/softfloat.cpp.o
[ 10%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/split.cpp.o
[ 10%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/stat.cpp.o
[ 10%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/stat.dispatch.cpp.o
[ 10%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/stl.cpp.o
[ 10%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/system.cpp.o
[ 10%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/tables.cpp.o
[ 10%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/trace.cpp.o
[ 10%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/types.cpp.o
[ 10%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/umatrix.cpp.o
[ 10%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/va_intel.cpp.o
[ 10%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/opencl_kernels_core.cpp.o
[ 10%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/mathfuncs_core.sse2.cpp.o
[ 10%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/convert.sse4_1.cpp.o
[ 10%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/stat.sse4_2.cpp.o
[ 10%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/convert.fp16.cpp.o
[ 11%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/mathfuncs_core.avx.cpp.o
[ 11%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/convert.avx2.cpp.o
[ 11%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/mathfuncs_core.avx2.cpp.o
[ 11%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/stat.avx2.cpp.o
[ 11%] Linking CXX shared library ../../lib/libopencv_core.so
[ 11%] Built target opencv_core
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2
`
Not sure what I need to change

**Comment by Yumin-Sun-00** [comment]
@whizzzkid  you should specific to the readme that the script will not help to check the make complete.

Thank you for this helpful script.

**Comment by whizzzkid** [comment]
@waschbaer00 just updated the script, now the installation will `fail` if a command is not completed.
