### ISSUE TITLE
Script modifications suggestion.

### ISSUE THREAD

**Issue by AndrewVGr** [whizzzkid/opencv-complete-build-cuda#2]
Hello!

Thank you for such a helpful script.

I suggest you to configure following cmake options (as shown in https://github.com/opencv/opencv/issues/9549):

-DBUILD_PROTOBUF=OFF
-DPROTOBUF_UPDATE_FILES=ON

Without these options compilation fails with different protobuf errors. I've checked this on protobuf versions 3.4.x and 3.5.x - in both cases these options let me avoid error messages.

**Comment by whizzzkid** [comment]
It works for me, probably because I have protobuf built from sources. I am not sure, if adding these flags will do any good. This script works fine as of today.

**Comment by Yumin-Sun-00** [comment]
I think build with protobuf should be recommend. If you have error, than should be the dependencies is not installed correctly, from my opinion. @AndrewVGr 

A lot of thanks to this script.

**Comment by whizzzkid** [comment]
@waschbaer00  you're welcome, @AndrewVGr  the script stays as is.
